language: python
python:
- '3.4'
addons:
  apt:
    packages:
    - enchant
install:
- pip install -r requirements.txt
- npm install webpagetest -g
script:
- nikola build
- fab linkchecker
- fab w3c_checks
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
    - edwin@wordspeak.org
  pushover:
    on_success: always
    on_failure: always
    api_key:
      secure: hPTvigjDJHe+AmoY7diE3V0qNQAV56zfH6fw8ZxFd8XcceKBmXm5HpdXEl7V9hdh+xBUW0Jz1/FSaSHuWJoteAUE2ABx4ISjEaud1hvVH9QLQSuNWIfcQGsRKTO2V1Dybd20sKc1oyluj/0gs+eyIYae1O81RUEGsRzES01auC+I0MjXVRZBtq5cDnjYhbN/250Bby4RXW2q+1e6Tn5hIaoLITukpYQqOxy2uCJQ9KHRmy3sBj4mSv4gNA5RcaV9N9OqPN3KcHVqmFMxPrfP/ZSv6XB57wT0lyi8fElhUM+yFPzjCYQF1izIxnutL/vNKfozGipfEuelUWiQzfVX3tOKMgt/1zZt1ArIdGK5wCy4opTEQ7b3NwUeOfnpO0DBSX3B3WM9ux5osNQhf5DL2GBZSmyebOOcYz2QZ47KKJZZ8Frc18a4LongASN6ZhKwOr0CEOGFiMG+NcThunOpOYypzF1pE+e/myny6qtEUNWJNA9+M2UQF1d8szV3dXskVUpFl48QCI4JL3rslBbeQcpuJrxl0ghB2UhdF98QDnLPBoST8Zx8ch7/Jg0YNeot2bQNDe/de8OcWO7tRSpWQGT7d3wyq9T9JUq/vODmJdeYK3ugXCRs5lsPnu00lRrAlafPah3SVgcRSBYRZ0/zOo0KA77QlH/QrXnpPthUUC8=
    users:
      secure: TRDaNchMd1zUtviPy0Nt2HZN43s1z6AWERlxU94wSNjM+/NgI5rzefUsuo8A46pGqttGaSxDtsEHv5/alcsvHxyB9jqlp5RTIalqH6I1waWSMXGW6PGN++z6a8nX+NTOIlGBmXPBN4h0oUZ5jH2mMgCWl/u9JRPJewY7f8DyViYB+ugxgMLWD3lrcgzgaacPd65DLzYZZXqB/8SGmOdnvzJvzAMY8t7CbD8K9w9/KKPz7a8+JawiOUEUKK/eVqBlb+0G1vFT282brebvMTTg5xvMMGxd6VcWmXoyS8XgDklOjZJVR/IkjDhplqhnUy3C2bgvxqMAdRhS35itbFPTNNCK/V427G3UPGbWeBoB40U39PpvY8q2OP10P62Xh2z6zFjiOHFzt6iTvfhRzsKin00UZGbiDJ6f4J3pEtcxmpd7g9R+wd65nkwHlt0i8vFFWFS/yMvtHdG0eqTjAkDxkxUFunhCQfG5CXi1jaygzjx4xxz06kSibvVH2jTmkC3HOgFHhIf6WjA8r2UI1C9KF1X/BToIb5F4ZjOgRFgrMTOJR8bGkIUT7O4UMRScsNsK8NB+dq3lu9ILsWZHe0uDNZRxqtokqCAqibQjkAY45AeKv45iLb/OVkwbxkMLSakSeYLkr+QDKg8XVR55zBRvf6s5kSkNHC3FgMBD0R/Wpys=
