
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import os
import time

# Data about this site
BLOG_AUTHOR = "Edwin Steele"
BLOG_TITLE = "Wordspeak"
BLOG_URL = "http://www.wordspeak.org"
BLOG_EMAIL = "edwin@wordspeak.org"
BLOG_DESCRIPTION = "Edwin's writings."


# post_pages contains (wildcard, destination, template, use_in_feed) tuples.
#
# The wildcard is used to generate a list of reSt source files
# (whatever/thing.txt).
# That fragment must have an associated metadata file (whatever/thing.meta),
# and opcionally translated files (example for spanish, with code "es"):
#     whatever/thing.txt.es and whatever/thing.meta.es
#
# From those files, a set of HTML fragment files will be generated:
# cache/whatever/thing.html (and maybe cache/whatever/thing.html.es)
#
# These files are combinated with the template to produce rendered
# pages, which will be placed at
# output / TRANSLATIONS[lang] / destination / pagename.html
#
# where "pagename" is specified in the metadata file.
#
# if use_in_feed is True, then those posts will be added to the site's
# rss feeds.
#

post_pages = (
    ("posts/*.txt", "posts", "post.tmpl", True),
    ("posts/*.wp", "posts", "post.tmpl", True),
    ("stories/*.txt", "pages", "story.tmpl", False),
)

# One or more folders containing files to be copied as-is into the output.
# The format is a dictionary of "source" "relative destination".
# Default is:
# FILES_FOLDERS = {'files': '' }
# Which means copy 'files' into 'output'

post_compilers = {
    "rest": ('.txt', '.rst'),
    "markdown": ('.md', '.mdown', '.markdown', ".wp"),
    "html": ('.html', '.htm')
    }

DEFAULT_LANG = "en"
TRANSLATIONS = {
    "en": "",
    }

# Paths for different autogenerated bits. These are combined with the
# translation paths.

# Final locations are:
# output / TRANSLATION[lang] / TAG_PATH / index.html (list of tags)
# output / TRANSLATION[lang] / TAG_PATH / tag.html (list of posts for a tag)
# output / TRANSLATION[lang] / TAG_PATH / tag.xml (RSS feed for a tag)
TAG_PATH = "categories"

# If TAG_PAGES_ARE_INDEXES is set to True, each tag's page will contain
# the posts themselves. If set to False, it will be just a list of links.
TAG_PAGES_ARE_INDEXES = True

# Final location is output / TRANSLATION[lang] / INDEX_PATH / index-*.html
INDEX_PATH = ""
# Final locations for the archives are:
# output / TRANSLATION[lang] / ARCHIVE_PATH / ARCHIVE_FILENAME
# output / TRANSLATION[lang] / ARCHIVE_PATH / YEAR / index.html
ARCHIVE_PATH = ""
ARCHIVE_FILENAME = "archive.html"
# Final locations are:
# output / TRANSLATION[lang] / RSS_PATH / rss.xml
RSS_PATH = ""

SLUG_TAG_PATH = True

REDIRECTIONS = [
    ("2005/11/21/patience-grasshopper",
        "/posts/20051121patience-grasshopper.html"),
    ("2006/01/30/kosciuszko",
        "/posts/20060130kosciuszko.html"),
    ("2006/02/04/four-things",
        "/posts/20060204four-things.html"),
    ("2006/02/18/the-muhammed-cartoons-whats-really-going-on",
        "/posts/20060218the-muhammed-cartoons-whats-really-going-on.html"),
    ("2006/04/02/farewell-wireless-broadband",
        "/posts/20060402farewell-wireless-broadband.html"),
    ("2006/05/27/justifying-tax-cuts-for-the-rich",
        "/posts/20060527justifying-tax-cuts-for-the-rich.html"),
    ("2006/07/28/jenolan-caves-limestone-and-country-air",
        "/posts/20060728jenolan-caves-limestone-and-country-air.html"),
    ("2006/09/27/information-security-in-action-or-not-after-theft",
        "/posts/20060927information-security-in-action-or-not-after-theft.html"),
    ("2006/12/23/my-year-in-cities-2006",
        "/posts/20061223my-year-in-cities-2005.html"),
    ("2006/12/23/my-year-in-cities-2005",
        "/posts/20061223my-year-in-cities-2006.html"),
    ("2007/01/03/fiveish-things",
        "/posts/20070103fiveish-things.html"),
    ("2007/01/04/rock-climbing-at-barrenjoey-christmas-06",
        "/posts/20070104rock-climbing-at-barrenjoey-christmas-06.html"),
    ("2007/06/17/ship-run-aground-pasha-bulker",
        "/posts/20070617ship-run-aground-pasha-bulker.html"),
    ("2007/08/15/so-long-hong-kong",
        "/posts/20070815so-long-hong-kong.html"),
    ("2008/02/04/stone-churches-in-western-sydney-and-blue-mountains",
        "/posts/20080204stone-churches-in-western-sydney-and-blue-mountains.html"),
    ("2011/02/24/finding-a-new-home-for-my-photos",
        "/posts/20110224finding-a-new-home-for-my-photos.html"),
    ("2011/11/13/our-chicago-video-and-photos-are-up",
        "/posts/20111113our-chicago-video-and-photos-are-up.html")
]

DEPLOY_COMMANDS = [
    "rsync -av /Users/esteele/Code/wordspeak.org/output/ /Users/esteele/Sites/staging.wordspeak.org"
]

OUTPUT_FOLDER = 'output'
CACHE_FOLDER = 'cache'

# Filters to apply to the output.
# A directory where the keys are either: a file extensions, or
# a tuple of file extensions.
#
# And the value is a list of commands to be applied in order.
#
# Each command must be either:
#
# A string containing a '%s' which will
# be replaced with a filename. The command *must* produce output
# in place.
#
# Or:
#
# A python callable, which will be called with the filename as
# argument.
#
# By default, there are no filters.
FILTERS = {
#    ".jpg": ["jpegoptim --strip-all -m75 -v %s"],
}

# #############################################################################
# Image Gallery Options
# #############################################################################

# Galleries are folders in galleries/
# Final location of galleries will be output / GALLERY_PATH / gallery_name
GALLERY_PATH = "galleries"
THUMBNAIL_SIZE = 180
MAX_IMAGE_SIZE = 1280
USE_FILENAME_AS_TITLE = True

# #############################################################################
# HTML fragments and diverse things that are used by the templates
# #############################################################################

# Data about post-per-page indexes
INDEXES_TITLE = ""  # If this is empty, the default is BLOG_TITLE
INDEXES_PAGES = ""  # If this is empty, the default is 'old posts page %d' translated

# Name of the theme to use. Themes are located in themes/theme_name
THEME = 'site'

# date format used to display post dates. (str used by datetime.datetime.strftime)
DATE_FORMAT = '%Y-%m-%d %H:%M'

# Show only teasers in the index pages? Defaults to False.
# INDEX_TEASERS = False

# A HTML fragment describing the license, for the sidebar.
LICENSE = ""

# A small copyright notice for the page footer (in HTML)
CONTENT_FOOTER = 'Uncopyright. No rights reserved | <a href="/pages/licencing.html">Why give it away?</a>'
CONTENT_FOOTER = CONTENT_FOOTER.format(email=BLOG_EMAIL,
                                       author=BLOG_AUTHOR,
                                       date=time.gmtime().tm_year)

# To enable comments via Disqus, you need to create a forum at
# http://disqus.com, and set DISQUS_FORUM to the short name you selected.
# If you want to disable comments, set it to False.
DISQUS_FORUM = False

# Enable Addthis social buttons?
# Defaults to true
ADD_THIS_BUTTONS = False

# Modify the number of Post per Index Page
# Defaults to 10
# INDEX_DISPLAY_POST_COUNT = 10

# RSS_LINK is a HTML fragment to link the RSS or Atom feeds. If set to None,
# the base.tmpl will use the feed Nikola generates. However, you may want to
# change it for a feedburner feed or something else.
RSS_LINK = None

# A search form to search this site, for the sidebar. You can use a google
# custom search (http://www.google.com/cse/)
# Or a duckduckgo search: https://duckduckgo.com/search_box.html
# This example should work for pretty much any site we generate.
SEARCH_FORM = ""
# This search form is better for the "site" theme where it
# appears on the navigation bar
#SEARCH_FORM = """
#<!-- Custom search -->
#<form method="get" id="search" action="http://duckduckgo.com/"
# class="navbar-form pull-left">
#<input type="hidden" name="sites" value="%s"/>
#<input type="hidden" name="k8" value="#444444"/>
#<input type="hidden" name="k9" value="#D51920"/>
#<input type="hidden" name="kt" value="h"/>
#<input type="text" name="q" maxlength="255"
# placeholder="Search&hellip;" class="span2" style="margin-top: 4px;"/>
#<input type="submit" value="DuckDuckGo Search" style="visibility: hidden;" />
#</form>
#<!-- End of custom search -->
#""" % BLOG_URL

# Google analytics or whatever else you use. Added to the bottom of <body>
# in the default template (base.tmpl).
ANALYTICS = """
    """

# Put in global_context things you want available on all your templates.
# It can be anything, data, functions, modules, etc.
GLOBAL_CONTEXT = {
    'analytics': ANALYTICS,
    'blog_author': BLOG_AUTHOR,
    'blog_title': BLOG_TITLE,
    'blog_url': BLOG_URL,
    'blog_desc': BLOG_DESCRIPTION,
    'date_format': DATE_FORMAT,
    'translations': TRANSLATIONS,
    'license': LICENSE,
    'search_form': SEARCH_FORM,
    'disqus_forum': DISQUS_FORUM,
    'content_footer': CONTENT_FOOTER,
    'rss_path': RSS_PATH,
    'rss_link': RSS_LINK,
    # Locale-dependent links for the sidebar
    # You should provide a key-value pair for each used language.
    'sidebar_links': {
        DEFAULT_LANG: (
            ('/pages/about.html', 'About'),
            ('/pages/projects.html', 'Projects'),
            ('/pages/photos-and-video.html', 'Photos and Video'),
            ('/' + os.path.join(ARCHIVE_PATH, ARCHIVE_FILENAME), 'Archives'),
            ('/rss.xml', 'RSS Feed'),
            ),
        }
    }
