name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        sudo apt-get install enchant
        pip install -r requirements.txt
    - name: Build site
      run: ./wordspeak_tool.py build
    - name: Deploy to staging
      uses: burnett01/rsync-deployments@5.2
      with:
        # Switches need to match arguments in authorised_keys
        switches: '--rsync-path=/usr/bin/openrsync -av --delete'
        path: output/
        remote_path: ${{ secrets.STAGING_DEPLOY_PATH }}
        remote_host: ${{ secrets.STAGING_DEPLOY_HOST }}
        remote_user: ${{ secrets.STAGING_DEPLOY_USER }}
        remote_key: ${{ secrets.STAGING_DEPLOY_KEY }}
    - name: Run tests
      run: |
        #./wordspeak_tool.py spellchecker
        echo $PATH
    - name: Deploy to prod (master only)
      uses: burnett01/rsync-deployments@5.2
      with:
        # Switches need to match arguments in authorised_keys
        switches: '--rsync-path=/usr/bin/openrsync -av --delete'
        path: output/
        remote_path: ${{ secrets.PROD_DEPLOY_PATH }}
        remote_host: ${{ secrets.PROD_DEPLOY_HOST }}
        remote_user: ${{ secrets.PROD_DEPLOY_USER }}
        remote_key: ${{ secrets.PROD_DEPLOY_KEY }}
      if: github.ref == 'refs/heads/master'
