name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build site
      run: ./wordspeak_tool.py build
    - name: Deploy to staging
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: output/
        remote_path: ${{ secrets.STAGING_DEPLOY_PATH }}
        remote_host: ${{ secrets.STAGING_DEPLOY_HOST }}
        remote_user: ${{ secrets.STAGING_DEPLOY_USER }}
        remote_key: ${{ secrets.STAGING_DEPLOY_KEY }}
    - name: Run tests  (XXX need to inject staging deploy)
      run: |
        ./wordspeak_tool.py spellchecker
        echo $PATH
    #- name: Deploy to prod (master only)
    #  uses: reggionick/s3-deploy@v3
    #  with:
    #    folder: output
    #    bucket: ${{ secrets.PROD_S3_BUCKET }}
    #    bucket-region: ${{ secrets.S3_BUCKET_REGION }}
    #    dist-id: ${{ secrets.PROD_CLOUDFRONT_DISTRIBUTION_ID }}
    #    delete-removed: true
    #    no-cache: true
    #    private: true
    #  env:
    #    AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
    #    AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
    #  if: github.ref == 'refs/heads/master'
